### ISSUE TITLE
Syntax errors 

### ISSUE THREAD

**Issue by CraftingMania** [MCrafterss/Essentials-Op#7]
help me i tried evrything i erased all the code except on enable and ondisable public functions but the same error i think it is in use\pocketmine\.........

but i dont know which one in use\pocketmine\..........  is wrong

**Comment by CraftingMania** [comment]
lol i typed namspace instead of namespace but the other errors because i miss understand php i am relearning at the momment but after all thx taha alot

**Comment by PocketKiller** [comment]
now look at the idea i gave you and do it :P

**Comment by CraftingMania** [comment]
all i need now to know what is the problem with anti ban and anti kick i will fix that asap
