### ISSUE TITLE
base class loader not found

### ISSUE THREAD

**Issue by CraftingMania** [MCrafterss/Essentials-Op#8]
i did evrything fixed all syntax errors and that what i get as a result .  :disappointed: :cry: :sob: :skull: :fire: 

@MCrafterss/developers help please

**Comment by PocketKiller** [comment]
you wanna submit.. lol

**Comment by PocketKiller** [comment]
i'll check

**Comment by PocketKiller** [comment]
show crashdump

**Comment by CraftingMania** [comment]
it doesnt crash

here is the console

05:09:28] [INFO]: Loading DevTools v1.10.0
[05:09:28] [INFO]: Loading PvPWorlds v1
[05:09:28] [INFO]: Enabling DevTools v1.10.0
[05:09:28] [INFO]: Loading source plugin Essentials-Op v1
[05:09:28] [CRITICAL]: ClassNotFoundException: "Class mcrafters\PluginBase not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[05:09:28] [INFO]: Disabling DevTools v1.10.0

**Comment by PocketKiller** [comment]
... learn OOP

**Comment by CraftingMania** [comment]
you mean learn php and also that isnt in the php course you should say learn pocketmine api which i cant find a place to learn it in

**Comment by CraftingMania** [comment]
omg didnt know that it was that simple

**Comment by PocketKiller** [comment]
@CraftingMania That is PHP, not pocketmine api.

**Comment by CraftingMania** [comment]
nvm ignore what i said
